[build]
builder = "NIXPACKS"

[deploy]
startCommand = "streamlit run streamlit_annotation_railway.py --server.port=$PORT --server.address=0.0.0.0"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
